---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: clone a repo
    git: repo=https://github.com/srinivas30240/Final_Edureka_project.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 docker build -t myadd:ansible2 .
  - name: create container
    command: docker run -itd -P myadd:ansible2
  - name: Login to Docker Hub
      docker_login:
        username: sri33
        password: Srinivas36*

    - name: Push Docker image to Docker Hub
      command: docker push sri33/myapp:latest
