kind: Deployment
apiVersion: apps/v1
metadata:
    name: abctechnologies-dep
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: abc-tech-app
    template:
        metadata:
            labels:
                app: abc-tech-app
        spec:
            containers:
                - image: sri33/edureka:abctech1
                  name: app
---

kind: Service
apiVersion: v1
metadata:
    name: abc-tech-service
spec:
    type: NodePort
    selector:
        app: abc-tech-app
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port





