kind: Deployment
apiVersion: apps/v1
metadata:
  name: abctechnologies-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abctechnologies
  template:
    metadata:
      name: abctechnologies
      labels:
        app: abctechnologies
    spec:
      containers:
       - name: app
         image: sri33/edureka:abctech
        
---
kind: Service
apiVersion: v1
metadata:
   name: abctechnologies-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector: 
    app: abctechnologies
